/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.9
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDomain200Response,
  CreateDomain409Response,
  CreateDomainRequest,
  CreateLink429Response,
  GetLink401Response,
} from '../models/index';
import {
    CreateDomain200ResponseFromJSON,
    CreateDomain200ResponseToJSON,
    CreateDomain409ResponseFromJSON,
    CreateDomain409ResponseToJSON,
    CreateDomainRequestFromJSON,
    CreateDomainRequestToJSON,
    CreateLink429ResponseFromJSON,
    CreateLink429ResponseToJSON,
    GetLink401ResponseFromJSON,
    GetLink401ResponseToJSON,
} from '../models/index';

export interface CreateDomainOperationRequest {
    createDomainRequest?: CreateDomainRequest;
}

/**
 * 
 */
export class DomainsApi extends runtime.BaseAPI {

    /**
     * Create a domain
     */
    async createDomainRaw(requestParameters: CreateDomainOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDomain200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/domains/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDomainRequestToJSON(requestParameters['createDomainRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDomain200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a domain
     */
    async createDomain(requestParameters: CreateDomainOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDomain200Response> {
        const response = await this.createDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
