/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Stats200Response,
  Stats400Response,
  StatsRequest,
} from '../models/index';
import {
    Stats200ResponseFromJSON,
    Stats200ResponseToJSON,
    Stats400ResponseFromJSON,
    Stats400ResponseToJSON,
    StatsRequestFromJSON,
    StatsRequestToJSON,
} from '../models/index';

export interface StatsOperationRequest {
    statsRequest?: StatsRequest;
}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI {

    /**
     * Get statistics of a link
     */
    async statsRaw(requestParameters: StatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stats200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/stats`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StatsRequestToJSON(requestParameters['statsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Stats200ResponseFromJSON(jsonValue));
    }

    /**
     * Get statistics of a link
     */
    async stats(requestParameters: StatsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stats200Response> {
        const response = await this.statsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
