/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Team200Response,
} from '../models/index';
import {
    Team200ResponseFromJSON,
    Team200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TeamApi extends runtime.BaseAPI {

    /**
     * Get teams of user
     */
    async teamRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/team`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Team200ResponseFromJSON(jsonValue));
    }

    /**
     * Get teams of user
     */
    async team(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team200Response> {
        const response = await this.teamRaw(initOverrides);
        return await response.value();
    }

}
