/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.2
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetLink401Response,
  GetTeams200Response,
} from '../models/index';
import {
    GetLink401ResponseFromJSON,
    GetLink401ResponseToJSON,
    GetTeams200ResponseFromJSON,
    GetTeams200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TeamsApi extends runtime.BaseAPI {

    /**
     * Get teams of user
     */
    async getTeamsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTeams200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/teams`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTeams200ResponseFromJSON(jsonValue));
    }

    /**
     * Get teams of user
     */
    async getTeams(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTeams200Response> {
        const response = await this.getTeamsRaw(initOverrides);
        return await response.value();
    }

}
