/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Authentification200Response
 */
export interface Authentification200Response {
    /**
     * 
     * @type {string}
     * @memberof Authentification200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the Authentification200Response interface.
 */
export function instanceOfAuthentification200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Authentification200ResponseFromJSON(json: any): Authentification200Response {
    return Authentification200ResponseFromJSONTyped(json, false);
}

export function Authentification200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authentification200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function Authentification200ResponseToJSON(value?: Authentification200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

