/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.9
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDomain200Response
 */
export interface CreateDomain200Response {
    /**
     * Domain
     * @type {string}
     * @memberof CreateDomain200Response
     */
    domain?: string;
    /**
     * Redirect URL for the root of the domain
     * @type {string}
     * @memberof CreateDomain200Response
     */
    rootUrl?: string;
}

/**
 * Check if a given object implements the CreateDomain200Response interface.
 */
export function instanceOfCreateDomain200Response(value: object): value is CreateDomain200Response {
    return true;
}

export function CreateDomain200ResponseFromJSON(json: any): CreateDomain200Response {
    return CreateDomain200ResponseFromJSONTyped(json, false);
}

export function CreateDomain200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDomain200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'rootUrl': json['root_url'] == null ? undefined : json['root_url'],
    };
}

export function CreateDomain200ResponseToJSON(json: any): CreateDomain200Response {
    return CreateDomain200ResponseToJSONTyped(json, false);
}

export function CreateDomain200ResponseToJSONTyped(value?: CreateDomain200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'root_url': value['rootUrl'],
    };
}

