/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.9
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDomainRequest
 */
export interface CreateDomainRequest {
    /**
     * Team API ID
     * @type {string}
     * @memberof CreateDomainRequest
     */
    teamId: string;
    /**
     * Domain
     * @type {string}
     * @memberof CreateDomainRequest
     */
    domain: string;
    /**
     * Redirect URL for the root of the domain
     * @type {string}
     * @memberof CreateDomainRequest
     */
    rootUrl?: string;
}

/**
 * Check if a given object implements the CreateDomainRequest interface.
 */
export function instanceOfCreateDomainRequest(value: object): value is CreateDomainRequest {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function CreateDomainRequestFromJSON(json: any): CreateDomainRequest {
    return CreateDomainRequestFromJSONTyped(json, false);
}

export function CreateDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['team_id'],
        'domain': json['domain'],
        'rootUrl': json['root_url'] == null ? undefined : json['root_url'],
    };
}

export function CreateDomainRequestToJSON(json: any): CreateDomainRequest {
    return CreateDomainRequestToJSONTyped(json, false);
}

export function CreateDomainRequestToJSONTyped(value?: CreateDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_id': value['teamId'],
        'domain': value['domain'],
        'root_url': value['rootUrl'],
    };
}

