/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.7
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Custom metadata for social previews
 * @export
 * @interface CreateLinkRequestMetatag
 */
export interface CreateLinkRequestMetatag {
    /**
     * Title for the link
     * @type {string}
     * @memberof CreateLinkRequestMetatag
     */
    title?: string;
    /**
     * Description for the link
     * @type {string}
     * @memberof CreateLinkRequestMetatag
     */
    description?: string;
    /**
     * Image URL for the link. Recommended: 1200X630px<br>Maximum size: 3Mb - Formats: PNG, JPEG, WebP and GIF.
     * @type {string}
     * @memberof CreateLinkRequestMetatag
     */
    image?: string;
}

/**
 * Check if a given object implements the CreateLinkRequestMetatag interface.
 */
export function instanceOfCreateLinkRequestMetatag(value: object): value is CreateLinkRequestMetatag {
    return true;
}

export function CreateLinkRequestMetatagFromJSON(json: any): CreateLinkRequestMetatag {
    return CreateLinkRequestMetatagFromJSONTyped(json, false);
}

export function CreateLinkRequestMetatagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLinkRequestMetatag {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function CreateLinkRequestMetatagToJSON(json: any): CreateLinkRequestMetatag {
    return CreateLinkRequestMetatagToJSONTyped(json, false);
}

export function CreateLinkRequestMetatagToJSONTyped(value?: CreateLinkRequestMetatag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'image': value['image'],
    };
}

