/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLink201Response
 */
export interface CreateLink201Response {
    /**
     * Link API ID
     * @type {string}
     * @memberof CreateLink201Response
     */
    id?: string;
    /**
     * Original URL
     * @type {string}
     * @memberof CreateLink201Response
     */
    url?: string;
    /**
     * Team API ID
     * @type {string}
     * @memberof CreateLink201Response
     */
    team?: string;
    /**
     * Folder API ID
     * @type {string}
     * @memberof CreateLink201Response
     */
    folderId?: string;
    /**
     * Domain
     * @type {string}
     * @memberof CreateLink201Response
     */
    domainId?: string;
    /**
     * Short code
     * @type {string}
     * @memberof CreateLink201Response
     */
    code?: string;
    /**
     * Label
     * @type {string}
     * @memberof CreateLink201Response
     */
    label?: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof CreateLink201Response
     */
    createdAt?: Date;
    /**
     * Modification date
     * @type {Date}
     * @memberof CreateLink201Response
     */
    updatedAt?: Date;
    /**
     * Expiration date
     * @type {Date}
     * @memberof CreateLink201Response
     */
    expiredAt?: Date;
}

/**
 * Check if a given object implements the CreateLink201Response interface.
 */
export function instanceOfCreateLink201Response(value: object): value is CreateLink201Response {
    return true;
}

export function CreateLink201ResponseFromJSON(json: any): CreateLink201Response {
    return CreateLink201ResponseFromJSONTyped(json, false);
}

export function CreateLink201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLink201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'team': json['team'] == null ? undefined : json['team'],
        'folderId': json['folder_id'] == null ? undefined : json['folder_id'],
        'domainId': json['domain_id'] == null ? undefined : json['domain_id'],
        'code': json['code'] == null ? undefined : json['code'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'expiredAt': json['expired_at'] == null ? undefined : (new Date(json['expired_at'])),
    };
}

export function CreateLink201ResponseToJSON(value?: CreateLink201Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url': value['url'],
        'team': value['team'],
        'folder_id': value['folderId'],
        'domain_id': value['domainId'],
        'code': value['code'],
        'label': value['label'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'expired_at': value['expiredAt'] == null ? undefined : ((value['expiredAt']).toISOString()),
    };
}

