/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFolder200Response
 */
export interface CreateFolder200Response {
    /**
     * Team API ID
     * @type {string}
     * @memberof CreateFolder200Response
     */
    teamId?: string;
    /**
     * Name
     * @type {string}
     * @memberof CreateFolder200Response
     */
    name?: string;
    /**
     * Parent Folder API ID (if any)
     * @type {string}
     * @memberof CreateFolder200Response
     */
    parentId?: string;
    /**
     * Parent Folder name (if any)
     * @type {string}
     * @memberof CreateFolder200Response
     */
    parentName?: string;
    /**
     * Color of folder
     * @type {string}
     * @memberof CreateFolder200Response
     */
    color?: CreateFolder200ResponseColorEnum;
}


/**
 * @export
 */
export const CreateFolder200ResponseColorEnum = {
    _48aefa: '48aefa',
    _2bcbba: '2bcbba',
    Fa8231: 'fa8231',
    Cd84f1: 'cd84f1',
    E74c3c: 'e74c3c',
    Ff9ff3: 'ff9ff3',
    Ffdd59: 'ffdd59',
    _2b2b2b: '2b2b2b'
} as const;
export type CreateFolder200ResponseColorEnum = typeof CreateFolder200ResponseColorEnum[keyof typeof CreateFolder200ResponseColorEnum];


/**
 * Check if a given object implements the CreateFolder200Response interface.
 */
export function instanceOfCreateFolder200Response(value: object): value is CreateFolder200Response {
    return true;
}

export function CreateFolder200ResponseFromJSON(json: any): CreateFolder200Response {
    return CreateFolder200ResponseFromJSONTyped(json, false);
}

export function CreateFolder200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolder200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'parentName': json['parent_name'] == null ? undefined : json['parent_name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function CreateFolder200ResponseToJSON(json: any): CreateFolder200Response {
    return CreateFolder200ResponseToJSONTyped(json, false);
}

export function CreateFolder200ResponseToJSONTyped(value?: CreateFolder200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_id': value['teamId'],
        'name': value['name'],
        'parent_id': value['parentId'],
        'parent_name': value['parentName'],
        'color': value['color'],
    };
}

