/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccessToken200Response
 */
export interface CreateAccessToken200Response {
    /**
     * Access token (JWT) valid for 1 hour
     * @type {string}
     * @memberof CreateAccessToken200Response
     */
    token?: string;
    /**
     * Refresh token valid for 1 month
     * @type {string}
     * @memberof CreateAccessToken200Response
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the CreateAccessToken200Response interface.
 */
export function instanceOfCreateAccessToken200Response(value: object): value is CreateAccessToken200Response {
    return true;
}

export function CreateAccessToken200ResponseFromJSON(json: any): CreateAccessToken200Response {
    return CreateAccessToken200ResponseFromJSONTyped(json, false);
}

export function CreateAccessToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccessToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
    };
}

export function CreateAccessToken200ResponseToJSON(value?: CreateAccessToken200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'refresh_token': value['refreshToken'],
    };
}

