/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditLink500Response
 */
export interface EditLink500Response {
    /**
     * 
     * @type {string}
     * @memberof EditLink500Response
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof EditLink500Response
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof EditLink500Response
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof EditLink500Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the EditLink500Response interface.
 */
export function instanceOfEditLink500Response(value: object): value is EditLink500Response {
    return true;
}

export function EditLink500ResponseFromJSON(json: any): EditLink500Response {
    return EditLink500ResponseFromJSONTyped(json, false);
}

export function EditLink500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditLink500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function EditLink500ResponseToJSON(json: any): EditLink500Response {
    return EditLink500ResponseToJSONTyped(json, false);
}

export function EditLink500ResponseToJSONTyped(value?: EditLink500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
    };
}

