/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderRequest
 */
export interface FolderRequest {
    /**
     * Team ID (displayed on dashboard)
     * @type {number}
     * @memberof FolderRequest
     */
    team: number;
}

/**
 * Check if a given object implements the FolderRequest interface.
 */
export function instanceOfFolderRequest(value: object): boolean {
    if (!('team' in value)) return false;
    return true;
}

export function FolderRequestFromJSON(json: any): FolderRequest {
    return FolderRequestFromJSONTyped(json, false);
}

export function FolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'team': json['team'],
    };
}

export function FolderRequestToJSON(value?: FolderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team': value['team'],
    };
}

