/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Folder200ResponseFoldersInner } from './Folder200ResponseFoldersInner';
import {
    Folder200ResponseFoldersInnerFromJSON,
    Folder200ResponseFoldersInnerFromJSONTyped,
    Folder200ResponseFoldersInnerToJSON,
} from './Folder200ResponseFoldersInner';

/**
 * 
 * @export
 * @interface Folder200Response
 */
export interface Folder200Response {
    /**
     * 
     * @type {Array<Folder200ResponseFoldersInner>}
     * @memberof Folder200Response
     */
    folders?: Array<Folder200ResponseFoldersInner>;
}

/**
 * Check if a given object implements the Folder200Response interface.
 */
export function instanceOfFolder200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Folder200ResponseFromJSON(json: any): Folder200Response {
    return Folder200ResponseFromJSONTyped(json, false);
}

export function Folder200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'folders': !exists(json, 'folders') ? undefined : ((json['folders'] as Array<any>).map(Folder200ResponseFoldersInnerFromJSON)),
    };
}

export function Folder200ResponseToJSON(value?: Folder200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'folders': value.folders === undefined ? undefined : ((value.folders as Array<any>).map(Folder200ResponseFoldersInnerToJSON)),
    };
}

