/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Folder200ResponseFoldersInner
 */
export interface Folder200ResponseFoldersInner {
    /**
     * Folder ID
     * @type {number}
     * @memberof Folder200ResponseFoldersInner
     */
    id?: number;
    /**
     * Folder name
     * @type {string}
     * @memberof Folder200ResponseFoldersInner
     */
    name?: string;
}

/**
 * Check if a given object implements the Folder200ResponseFoldersInner interface.
 */
export function instanceOfFolder200ResponseFoldersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Folder200ResponseFoldersInnerFromJSON(json: any): Folder200ResponseFoldersInner {
    return Folder200ResponseFoldersInnerFromJSONTyped(json, false);
}

export function Folder200ResponseFoldersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder200ResponseFoldersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function Folder200ResponseFoldersInnerToJSON(value?: Folder200ResponseFoldersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

