/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.2
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFolders200ResponseFoldersInner
 */
export interface GetFolders200ResponseFoldersInner {
    /**
     * Folder API ID
     * @type {string}
     * @memberof GetFolders200ResponseFoldersInner
     */
    id?: string;
    /**
     * Folder name
     * @type {string}
     * @memberof GetFolders200ResponseFoldersInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetFolders200ResponseFoldersInner interface.
 */
export function instanceOfGetFolders200ResponseFoldersInner(value: object): value is GetFolders200ResponseFoldersInner {
    return true;
}

export function GetFolders200ResponseFoldersInnerFromJSON(json: any): GetFolders200ResponseFoldersInner {
    return GetFolders200ResponseFoldersInnerFromJSONTyped(json, false);
}

export function GetFolders200ResponseFoldersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFolders200ResponseFoldersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetFolders200ResponseFoldersInnerToJSON(value?: GetFolders200ResponseFoldersInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

