/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.7
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLink200ResponseTagsInner
 */
export interface GetLink200ResponseTagsInner {
    /**
     * ID
     * @type {string}
     * @memberof GetLink200ResponseTagsInner
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof GetLink200ResponseTagsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetLink200ResponseTagsInner interface.
 */
export function instanceOfGetLink200ResponseTagsInner(value: object): value is GetLink200ResponseTagsInner {
    return true;
}

export function GetLink200ResponseTagsInnerFromJSON(json: any): GetLink200ResponseTagsInner {
    return GetLink200ResponseTagsInnerFromJSONTyped(json, false);
}

export function GetLink200ResponseTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLink200ResponseTagsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetLink200ResponseTagsInnerToJSON(json: any): GetLink200ResponseTagsInner {
    return GetLink200ResponseTagsInnerToJSONTyped(json, false);
}

export function GetLink200ResponseTagsInnerToJSONTyped(value?: GetLink200ResponseTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

