/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.10
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLink200ResponseGeolinksInnerConditionsInner
 */
export interface GetLink200ResponseGeolinksInnerConditionsInner {
    /**
     * Type of the condition 
     * @type {string}
     * @memberof GetLink200ResponseGeolinksInnerConditionsInner
     */
    type?: GetLink200ResponseGeolinksInnerConditionsInnerTypeEnum;
    /**
     * Value for the given type. Allowed values depend on "type": e.g., "US", "DE", "FR" for type "country"; "en", "fr", "de" for type "language"; "Android", "iOS" for type "system".
     * @type {string}
     * @memberof GetLink200ResponseGeolinksInnerConditionsInner
     */
    value?: string;
    /**
     * Operator to apply for the condition
     * @type {string}
     * @memberof GetLink200ResponseGeolinksInnerConditionsInner
     */
    operator?: GetLink200ResponseGeolinksInnerConditionsInnerOperatorEnum;
}


/**
 * @export
 */
export const GetLink200ResponseGeolinksInnerConditionsInnerTypeEnum = {
    Country: 'country',
    Language: 'language',
    System: 'system'
} as const;
export type GetLink200ResponseGeolinksInnerConditionsInnerTypeEnum = typeof GetLink200ResponseGeolinksInnerConditionsInnerTypeEnum[keyof typeof GetLink200ResponseGeolinksInnerConditionsInnerTypeEnum];

/**
 * @export
 */
export const GetLink200ResponseGeolinksInnerConditionsInnerOperatorEnum = {
    And: 'AND',
    Or: 'OR'
} as const;
export type GetLink200ResponseGeolinksInnerConditionsInnerOperatorEnum = typeof GetLink200ResponseGeolinksInnerConditionsInnerOperatorEnum[keyof typeof GetLink200ResponseGeolinksInnerConditionsInnerOperatorEnum];


/**
 * Check if a given object implements the GetLink200ResponseGeolinksInnerConditionsInner interface.
 */
export function instanceOfGetLink200ResponseGeolinksInnerConditionsInner(value: object): value is GetLink200ResponseGeolinksInnerConditionsInner {
    return true;
}

export function GetLink200ResponseGeolinksInnerConditionsInnerFromJSON(json: any): GetLink200ResponseGeolinksInnerConditionsInner {
    return GetLink200ResponseGeolinksInnerConditionsInnerFromJSONTyped(json, false);
}

export function GetLink200ResponseGeolinksInnerConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLink200ResponseGeolinksInnerConditionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'operator': json['operator'] == null ? undefined : json['operator'],
    };
}

export function GetLink200ResponseGeolinksInnerConditionsInnerToJSON(json: any): GetLink200ResponseGeolinksInnerConditionsInner {
    return GetLink200ResponseGeolinksInnerConditionsInnerToJSONTyped(json, false);
}

export function GetLink200ResponseGeolinksInnerConditionsInnerToJSONTyped(value?: GetLink200ResponseGeolinksInnerConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
        'operator': value['operator'],
    };
}

