/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.10
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UTM parameters
 * @export
 * @interface GetLink200ResponseUtm
 */
export interface GetLink200ResponseUtm {
    /**
     * utm_campaign
     * @type {string}
     * @memberof GetLink200ResponseUtm
     */
    campaign?: string;
    /**
     * utm_medium
     * @type {string}
     * @memberof GetLink200ResponseUtm
     */
    medium?: string;
    /**
     * utm_source
     * @type {string}
     * @memberof GetLink200ResponseUtm
     */
    source?: string;
    /**
     * utm_content
     * @type {string}
     * @memberof GetLink200ResponseUtm
     */
    content?: string;
}

/**
 * Check if a given object implements the GetLink200ResponseUtm interface.
 */
export function instanceOfGetLink200ResponseUtm(value: object): value is GetLink200ResponseUtm {
    return true;
}

export function GetLink200ResponseUtmFromJSON(json: any): GetLink200ResponseUtm {
    return GetLink200ResponseUtmFromJSONTyped(json, false);
}

export function GetLink200ResponseUtmFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLink200ResponseUtm {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign': json['campaign'] == null ? undefined : json['campaign'],
        'medium': json['medium'] == null ? undefined : json['medium'],
        'source': json['source'] == null ? undefined : json['source'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function GetLink200ResponseUtmToJSON(json: any): GetLink200ResponseUtm {
    return GetLink200ResponseUtmToJSONTyped(json, false);
}

export function GetLink200ResponseUtmToJSONTyped(value?: GetLink200ResponseUtm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign': value['campaign'],
        'medium': value['medium'],
        'source': value['source'],
        'content': value['content'],
    };
}

