/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.10
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatisticsRequest
 */
export interface GetStatisticsRequest {
    /**
     * Link API ID
     * @type {string}
     * @memberof GetStatisticsRequest
     */
    linkId: string;
    /**
     * Get statistics from this date
     * @type {Date}
     * @memberof GetStatisticsRequest
     */
    from?: Date;
    /**
     * Get statistics until this date
     * @type {Date}
     * @memberof GetStatisticsRequest
     */
    to?: Date;
}

/**
 * Check if a given object implements the GetStatisticsRequest interface.
 */
export function instanceOfGetStatisticsRequest(value: object): value is GetStatisticsRequest {
    if (!('linkId' in value) || value['linkId'] === undefined) return false;
    return true;
}

export function GetStatisticsRequestFromJSON(json: any): GetStatisticsRequest {
    return GetStatisticsRequestFromJSONTyped(json, false);
}

export function GetStatisticsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatisticsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'linkId': json['link_id'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
    };
}

export function GetStatisticsRequestToJSON(json: any): GetStatisticsRequest {
    return GetStatisticsRequestToJSONTyped(json, false);
}

export function GetStatisticsRequestToJSONTyped(value?: GetStatisticsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link_id': value['linkId'],
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
    };
}

