/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkTagsInner
 */
export interface LinkTagsInner {
    /**
     * ID
     * @type {string}
     * @memberof LinkTagsInner
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof LinkTagsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the LinkTagsInner interface.
 */
export function instanceOfLinkTagsInner(value: object): value is LinkTagsInner {
    return true;
}

export function LinkTagsInnerFromJSON(json: any): LinkTagsInner {
    return LinkTagsInnerFromJSONTyped(json, false);
}

export function LinkTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTagsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LinkTagsInnerToJSON(json: any): LinkTagsInner {
    return LinkTagsInnerToJSONTyped(json, false);
}

export function LinkTagsInnerToJSONTyped(value?: LinkTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

