/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * QR Code associated to the short link
 * @export
 * @interface LinkQrcode
 */
export interface LinkQrcode {
    /**
     * QR Code Data URL
     * @type {string}
     * @memberof LinkQrcode
     */
    data?: string;
}

/**
 * Check if a given object implements the LinkQrcode interface.
 */
export function instanceOfLinkQrcode(value: object): value is LinkQrcode {
    return true;
}

export function LinkQrcodeFromJSON(json: any): LinkQrcode {
    return LinkQrcodeFromJSONTyped(json, false);
}

export function LinkQrcodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkQrcode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function LinkQrcodeToJSON(json: any): LinkQrcode {
    return LinkQrcodeToJSONTyped(json, false);
}

export function LinkQrcodeToJSONTyped(value?: LinkQrcode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

