/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Custom metadata for social previews
 * @export
 * @interface LinkMetatag
 */
export interface LinkMetatag {
    /**
     * Title of the link
     * @type {string}
     * @memberof LinkMetatag
     */
    title?: string;
    /**
     * Description of the link
     * @type {string}
     * @memberof LinkMetatag
     */
    description?: string;
    /**
     * Image URL of the link
     * @type {string}
     * @memberof LinkMetatag
     */
    image?: string;
}

/**
 * Check if a given object implements the LinkMetatag interface.
 */
export function instanceOfLinkMetatag(value: object): value is LinkMetatag {
    return true;
}

export function LinkMetatagFromJSON(json: any): LinkMetatag {
    return LinkMetatagFromJSONTyped(json, false);
}

export function LinkMetatagFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkMetatag {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function LinkMetatagToJSON(json: any): LinkMetatag {
    return LinkMetatagToJSONTyped(json, false);
}

export function LinkMetatagToJSONTyped(value?: LinkMetatag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'image': value['image'],
    };
}

