/* tslint:disable */
/* eslint-disable */
/**
 * URLR API Reference
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul><li>All dates follow **ISO-8601** format</li><li>Most errors follow **RFC 9457** standard</li><li>All responses are delivered in English</li></ul>
 *
 * The version of the OpenAPI document: 1.12
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UTM parameters
 * @export
 * @interface LinkUtm
 */
export interface LinkUtm {
    /**
     * utm_campaign
     * @type {string}
     * @memberof LinkUtm
     */
    campaign?: string;
    /**
     * utm_medium
     * @type {string}
     * @memberof LinkUtm
     */
    medium?: string;
    /**
     * utm_source
     * @type {string}
     * @memberof LinkUtm
     */
    source?: string;
    /**
     * utm_content
     * @type {string}
     * @memberof LinkUtm
     */
    content?: string;
}

/**
 * Check if a given object implements the LinkUtm interface.
 */
export function instanceOfLinkUtm(value: object): value is LinkUtm {
    return true;
}

export function LinkUtmFromJSON(json: any): LinkUtm {
    return LinkUtmFromJSONTyped(json, false);
}

export function LinkUtmFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkUtm {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign': json['campaign'] == null ? undefined : json['campaign'],
        'medium': json['medium'] == null ? undefined : json['medium'],
        'source': json['source'] == null ? undefined : json['source'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function LinkUtmToJSON(json: any): LinkUtm {
    return LinkUtmToJSONTyped(json, false);
}

export function LinkUtmToJSONTyped(value?: LinkUtm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign': value['campaign'],
        'medium': value['medium'],
        'source': value['source'],
        'content': value['content'],
    };
}

