/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReduceLink200Response
 */
export interface ReduceLink200Response {
    /**
     * Original URL
     * @type {string}
     * @memberof ReduceLink200Response
     */
    url?: string;
    /**
     * Expiration date
     * @type {string}
     * @memberof ReduceLink200Response
     */
    expiredAt?: string;
    /**
     * Team ID (displayed on dashboard)
     * @type {number}
     * @memberof ReduceLink200Response
     */
    team?: number;
    /**
     * Folder ID (displayed on dashboard)
     * @type {number}
     * @memberof ReduceLink200Response
     */
    folder?: number;
    /**
     * Short code
     * @type {string}
     * @memberof ReduceLink200Response
     */
    urlCode?: string;
    /**
     * Domain
     * @type {string}
     * @memberof ReduceLink200Response
     */
    domain?: string;
    /**
     * HTTP status code
     * @type {number}
     * @memberof ReduceLink200Response
     */
    code?: number;
}

/**
 * Check if a given object implements the ReduceLink200Response interface.
 */
export function instanceOfReduceLink200Response(value: object): boolean {
    return true;
}

export function ReduceLink200ResponseFromJSON(json: any): ReduceLink200Response {
    return ReduceLink200ResponseFromJSONTyped(json, false);
}

export function ReduceLink200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReduceLink200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'expiredAt': json['expired_at'] == null ? undefined : json['expired_at'],
        'team': json['team'] == null ? undefined : json['team'],
        'folder': json['folder'] == null ? undefined : json['folder'],
        'urlCode': json['url_code'] == null ? undefined : json['url_code'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ReduceLink200ResponseToJSON(value?: ReduceLink200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'expired_at': value['expiredAt'],
        'team': value['team'],
        'folder': value['folder'],
        'url_code': value['urlCode'],
        'domain': value['domain'],
        'code': value['code'],
    };
}

