/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReduceLink400Response
 */
export interface ReduceLink400Response {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ReduceLink400Response
     */
    code?: number;
    /**
     * Error code
     * @type {number}
     * @memberof ReduceLink400Response
     */
    error?: number;
    /**
     * Message describing the error
     * @type {string}
     * @memberof ReduceLink400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ReduceLink400Response interface.
 */
export function instanceOfReduceLink400Response(value: object): boolean {
    return true;
}

export function ReduceLink400ResponseFromJSON(json: any): ReduceLink400Response {
    return ReduceLink400ResponseFromJSONTyped(json, false);
}

export function ReduceLink400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReduceLink400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ReduceLink400ResponseToJSON(value?: ReduceLink400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'error': value['error'],
        'message': value['message'],
    };
}

