/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReduceLink400Response
 */
export interface ReduceLink400Response {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ReduceLink400Response
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof ReduceLink400Response
     */
    error?: number;
    /**
     * Message describing the error
     * @type {string}
     * @memberof ReduceLink400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ReduceLink400Response interface.
 */
export function instanceOfReduceLink400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReduceLink400ResponseFromJSON(json: any): ReduceLink400Response {
    return ReduceLink400ResponseFromJSONTyped(json, false);
}

export function ReduceLink400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReduceLink400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ReduceLink400ResponseToJSON(value?: ReduceLink400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'error': value.error,
        'message': value.message,
    };
}

