/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats200Response
 */
export interface Stats200Response {
    /**
     * Clicks
     * @type {number}
     * @memberof Stats200Response
     */
    clicks?: number;
    /**
     * Unique clicks
     * @type {number}
     * @memberof Stats200Response
     */
    uniqueClicks?: number;
}

/**
 * Check if a given object implements the Stats200Response interface.
 */
export function instanceOfStats200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Stats200ResponseFromJSON(json: any): Stats200Response {
    return Stats200ResponseFromJSONTyped(json, false);
}

export function Stats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clicks': !exists(json, 'clicks') ? undefined : json['clicks'],
        'uniqueClicks': !exists(json, 'uniqueClicks') ? undefined : json['uniqueClicks'],
    };
}

export function Stats200ResponseToJSON(value?: Stats200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clicks': value.clicks,
        'uniqueClicks': value.uniqueClicks,
    };
}

