/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats400Response
 */
export interface Stats400Response {
    /**
     * 
     * @type {number}
     * @memberof Stats400Response
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats400Response
     */
    error?: number;
}

/**
 * Check if a given object implements the Stats400Response interface.
 */
export function instanceOfStats400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Stats400ResponseFromJSON(json: any): Stats400Response {
    return Stats400ResponseFromJSONTyped(json, false);
}

export function Stats400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function Stats400ResponseToJSON(value?: Stats400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'error': value.error,
    };
}

