/* tslint:disable */
/* eslint-disable */
/**
 * Developer API - URLR
 * API powering the features of URLR.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: contact@urlr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats400Response
 */
export interface Stats400Response {
    /**
     * 
     * @type {number}
     * @memberof Stats400Response
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats400Response
     */
    error?: number;
}

/**
 * Check if a given object implements the Stats400Response interface.
 */
export function instanceOfStats400Response(value: object): boolean {
    return true;
}

export function Stats400ResponseFromJSON(json: any): Stats400Response {
    return Stats400ResponseFromJSONTyped(json, false);
}

export function Stats400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Stats400ResponseToJSON(value?: Stats400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'error': value['error'],
    };
}

